import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics Book
  physicalAISidebar: [
    {
      type: 'category',
      label: 'Part I: Infrastructure',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Hardware & OS Configuration',
          collapsed: false,
          items: [
            'Part_I_Infrastructure/Chapter_1_Hardware_OS_Config/index',
            'Part_I_Infrastructure/Chapter_1_Hardware_OS_Config/hardware_comparison',
            'Part_I_Infrastructure/Chapter_1_Hardware_OS_Config/troubleshooting',
            'Part_I_Infrastructure/Chapter_1_Hardware_OS_Config/api_security',
          ],
        },
        {
          type: 'doc',
          id: 'Part_I_Infrastructure/Chapter_2_Edge_Ecosystem',
          label: 'Chapter 2: The Edge Ecosystem',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part II: ROS',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Part_II_ROS/Chapter_3_ROS_Architecture',
          label: 'Chapter 3: ROS 2 Architecture',
        },
        {
          type: 'doc',
          id: 'Part_II_ROS/Chapter_4_Body',
          label: 'Chapter 4: The Body (URDF & Kinematics)',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part III: Simulation',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Chapter 5: Physics in Gazebo',
          collapsed: false,
          items: [
            'Part_III_Simulation/Chapter_5_Physics_Gazebo/index',
            'Part_III_Simulation/Chapter_5_Physics_Gazebo/gazebo_plugins',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 6: Photorealism with NVIDIA Isaac Sim',
          collapsed: false,
          items: [
            'Part_III_Simulation/Chapter_6_Physically_Realistic_Sim/index',
            'Part_III_Simulation/Chapter_6_Physically_Realistic_Sim/usd_workflows',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Part IV: Perception',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Part_IV_Perception/Chapter_7_Sensors_VSLAM',
          label: 'Chapter 7: Sensors & VSLAM',
        },
        {
          type: 'doc',
          id: 'Part_IV_Perception/Chapter_8_Navigation',
          label: 'Chapter 8: Navigation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part V: AI Integration',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Part_V_AI_Integration/Chapter_9_Voice_Pipeline',
          label: 'Chapter 9: The Ears (Voice Pipeline)',
        },
        {
          type: 'category',
          label: 'Chapter 10: The Brain (LLM Action Planning)',
          collapsed: false,
          items: [
            'Part_V_AI_Integration/Chapter_10_Brain/index',
            'Part_V_AI_Integration/Chapter_10_Brain/prompt_templates',
          ],
        },
        {
          type: 'doc',
          id: 'Part_V_AI_Integration/Chapter_11_VLA',
          label: 'Chapter 11: Vision-Language-Action (VLA)',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part VI: Capstone',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Chapter 12: The Autonomous Humanoid',
          collapsed: false,
          items: [
            'Part_VI_Capstone/Chapter_12_Autonomous_Humanoid/index',
            'Part_VI_Capstone/Chapter_12_Autonomous_Humanoid/part_vi_autonomous_systems',
            'Part_VI_Capstone/Chapter_12_Autonomous_Humanoid/capstone_summary',
            'Part_VI_Capstone/Chapter_12_Autonomous_Humanoid/final_chapter',
            'Part_VI_Capstone/Chapter_12_Autonomous_Humanoid/book_summary',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
